// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6X6MkTI9QtvyFov9UwiWNG9JWqPOknok',
    appId: '1:474568791761:android:36e9010a0a17b400bf17f0',
    messagingSenderId: '474568791761',
    projectId: 'bylaive-aeeeb',
    databaseURL: 'https://bylaive-aeeeb-default-rtdb.firebaseio.com',
    storageBucket: 'bylaive-aeeeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCweJg_DikMrUy9LZPRzYqCZPP1LicJKqU',
    appId: '1:474568791761:ios:402d05040aa2ca53bf17f0',
    messagingSenderId: '474568791761',
    projectId: 'bylaive-aeeeb',
    databaseURL: 'https://bylaive-aeeeb-default-rtdb.firebaseio.com',
    storageBucket: 'bylaive-aeeeb.appspot.com',
    androidClientId: '474568791761-84c5qf9ks5qkr1bdf88hq43a5h6ctki4.apps.googleusercontent.com',
    iosBundleId: 'com.example.idute.idute',
  );
}
